// 34-Vue/Vuejs-D02/Lab/students/src/components/HeaderComponent.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">My App</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#"
            >Home <span class="sr-only">(current)</span></a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
</template>

<script>
export default {
  name: "HeaderComponent",
  props: {
    msg: String,
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped></style>

// 25-Angular/other/ang-startup-project/src/app/components/header/header.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { TaskService } from 'src/app/services/task.service';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  tasksCount:number=0;
  isLogged=false;
  constructor(private _taskService:TaskService,private _userService:UserService) { }

  ngOnInit(): void {

    //this.isLogged=this._userService.isLoggedIn();
    this._userService.logged.subscribe(status=>{
      this.isLogged=status;
    })

    this._taskService.get()
    .subscribe(
      (response:any)=>{
        this.tasksCount=response.Data.length;
      },
      (error:any)=>{}
    );
  }

}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" routerLink="/">Home </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/about']" >About</a>
          <!-- <a class="nav-link" routerLink="/about/{{id}}}/{{ddd}}" >About</a> -->
        </li>
        <li class="nav-item">
          <a class="nav-link" routerLink="/contact">Contact</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" routerLink="/tasks">Tasks ({{tasksCount}})</a>
          </li>
          <li class="nav-item" >
            <a class="nav-link" routerLink="/student">Students</a>
          </li>
          <li class="nav-item" >
            <a class="nav-link" routerLink="/student/create">Create Student</a>
          </li>
          <li class="nav-item" *ngIf="!isLogged">
            <a class="nav-link" routerLink="/user/login">Login</a>
          </li>
          <li class="nav-item"  *ngIf="isLogged">
            <a class="nav-link" routerLink="/user/logout">Logout</a>
          </li>
      
      </ul>
    </div>
  </nav>
